vmaas/common.go
vmaas/vulnerabilities.go

- fix mistake in processInputPackages
- remove logging

improve performance

---

vmaas/cache.go
vmaas/common.go
vmaas/common_test.go
vmaas/load.go
vmaas/types.go

feat(rhui): look up updates by repository path

---

vmaas/vulnerabilities.go

fix: return errata: [] instead of null

---

vmaas/cache.go
vmaas/load.go
vmaas/vulnerabilities.go
vmaas/vulnerabilities_test.go

feat: return errata for manually fixable cves

---

vmaas/common.go
vmaas/types.go

feat: return package name and evra in updates

---

vmaas/common.go
vmaas/types.go

needed to avoid parsing and sorting in Patch

fix(updates): sort availableUpdates

---

vmaas/vulnerabilities.go

fixing inconsistently returned unfixed CVEs based on if module list is provided or if isn't

fix: Don't evaluate module tests for unfixed CVE definitions, we're not looking for package updates anyway

---

vmaas/cache.go
vmaas/common.go
vmaas/load.go
vmaas/types.go
vmaas/vulnerabilities.go

feat(csaf): evaluate unfixed cves from csaf

---

vmaas/cache.go
vmaas/load.go
vmaas/vulnerabilities.go

fix(csaf): products for package names built from the same source

---

vmaas/vulnerabilities.go

fix: evaluate module tests for unfixed CVEs

---

vmaas/types.go
vmaas/vulnerabilities_test.go

fix: match cpe pattern substrings

---

vmaas/vulnerabilities.go

RHINENG-11156
depends on https://github.com/RedHatInsights/vmaas/pull/1128

fix(fixed_cves): use modules of fixed products in evaluation

---

.github/workflows/test.yml
vmaas/cache.go
vmaas/load.go
vmaas/options.go
vmaas/types.go
vmaas/vulnerabilities.go
vmaas/vulnerabilities_test.go

https://github.com/RedHatInsights/vmaas/commit/2ea99875f6038b7fad13fc66e07a2aadf9f45e18

feat(csaf): exclude kernel-alt

---

vmaas/common.go
vmaas/vulnerabilities.go

fix(csaf): duplicate cpes while processing

---

vmaas/common.go
vmaas/common_test.go
vmaas/options.go
vmaas/vulnerabilities.go

fix: options to disable newerReleasever from repos and csaf

---

example/main.go
vmaas/types.go
vmaas/vulnerabilities.go

feat: remove use_csaf from request struct

---

vmaas/vulnerabilities.go

it could happen that unfixed products are not created for nameID because srcNameID is already processed

fix: condition for skipping seen package names

---

.github/workflows/lint.yml
.github/workflows/test.yml
.golangci.yml
go.mod
go.sum
vmaas/types.go
vmaas/vulnerabilities.go

chore: update go version

---

vmaas/cache.go
vmaas/cache_test.go
vmaas/common.go
vmaas/errata_test.go
vmaas/load.go
vmaas/os.go
vmaas/types.go
vmaas/vmaas.go

feat: OS Release Vulnerability Report API

---

vmaas/load.go
vmaas/types.go

feat: add lifecycle_phase

---

vmaas/cache.go
vmaas/cache_test.go
vmaas/common.go
vmaas/cves.go
vmaas/errata.go
vmaas/load.go
vmaas/os.go
vmaas/packages.go
vmaas/patches.go
vmaas/pkglist.go
vmaas/pkgtree.go
vmaas/repos.go
vmaas/rpm_pkg_names.go
vmaas/srpm_pkg_names.go
vmaas/types.go
vmaas/vmaas.go

feat: rewrite vmaas dbchange endpoint in go
